version: "3"

services:
  proxy:
    build: .
    ports:
      - "8080:8080"
    environment:
      - TARGET_URL=ws://echo-server:9000
      - LOG_LEVEL=debug
    depends_on:
      - echo-server
    restart: unless-stopped

  echo-server:
    image: jmalloc/echo-server
    ports:
      - "9000:8080"
    restart: unless-stopped
